/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@dojoengine/recs";

export function defineContractComponents(world: World) {
  return {
	  Secret: (() => {
	    return defineComponent(
	      world,
	      { player: RecsType.BigInt, value: RecsType.Number },
	      {
	        metadata: {
	          name: "Secret",
	          types: ["contractaddress","u8"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  Square: (() => {
	    return defineComponent(
	      world,
	      { game_id: RecsType.BigInt, x: RecsType.Number, y: RecsType.Number, value: RecsType.Number },
	      {
	        metadata: {
	          name: "Square",
	          types: ["felt252","u8","u8","u8"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  TicTacToe: (() => {
	    return defineComponent(
	      world,
	      { game_id: RecsType.BigInt, player_one: RecsType.BigInt, player_two: RecsType.BigInt, turn: RecsType.Boolean },
	      {
	        metadata: {
	          name: "TicTacToe",
	          types: ["felt252","contractaddress","contractaddress","bool"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
  };
}
