/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@dojoengine/recs";

export function defineContractComponents(world: World) {
  return {
	  Secret: (() => {
	    return defineComponent(
	      world,
	      { player: RecsType.String, value: RecsType.Number },
	      {
	        metadata: {
	          name: "Secret",
	          types: [],
	        },
	      }
	    );
	  })(),
	  Square: (() => {
	    return defineComponent(
	      world,
	      { game_id: RecsType.Number, x: RecsType.Number, y: RecsType.Number, value: RecsType.Number },
	      {
	        metadata: {
	          name: "Square",
	          types: [],
	        },
	      }
	    );
	  })(),
	  TicTacToe: (() => {
	    return defineComponent(
	      world,
	      { game_id: RecsType.Number, turn: RecsType.Boolean },
	      {
	        metadata: {
	          name: "TicTacToe",
	          types: [],
	        },
	      }
	    );
	  })(),
  };
}
